sensor_kit_base_link:
  velodyne_top_base_link:
    x: 0.185
    y: 0.0
    z: 0.354
    roll: 0.0
    pitch: 0.0
    yaw: 1.575
  gnss_link:
    x: 0.0
    y: 0.0
    z: 0.1825
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  tamagawa/imu_link:
    x: 0.0
    y: 0.0
    z: 0.1825
    roll: 3.14159265359
    pitch: 0.0
    yaw: 3.14159265359
